### ISSUE TITLE
Try on Testnet but not get profit, why ?

### ISSUE THREAD

**Issue by anotherwilliam** [solidityengineering/mevbot#2]
Hello mate, I've tried it on the testnet and it works but why I don't get any profit ?

**Comment by solidityengineering** [comment]
> Hello mate, I've tried it on the testnet and it works but why I don't get any profit ?

This contract can be deployed on any network that supports evm, but will only work if it is run on ethereum and bnb chain (mainnet) networks.

If you deploy the contract on the testnet network it will still work but no profit will be obtained and only the remaining balance will go back into the wallet.

Running on the Ethereum network is highly recommended because there are many quality token pairs that can be found on uniswap v3/v2.

Transfer ETH for gas fees and WETH for trading to the contract/bot address. Click start and wait, after 15 minutes you can click the withdraw button to get the profit sent to your wallet.

**Comment by anotherwilliam** [comment]
Thanks for the complete answer, it works on ethereum mainnet and made my first profit with this mevbot.

**Comment by solidityengineering** [comment]
> Thanks for the complete answer, it works on ethereum mainnet and made my first profit with this mevbot.

your welcome, pleased to hear it
